In [2]:
import ipeadatapy as ipea
import pandas as pd

In [3]:
api_ipea = ipea.api_call('http://www.ipeadata.gov.br/api/odata4/')

In [4]:
api_ipea.shape

(6, 3)

In [5]:
api_ipea

          name       kind          url
0       Paises  EntitySet       Paises
1    Metadados  EntitySet    Metadados
2        Temas  EntitySet        Temas
3  Territorios  EntitySet  Territorios
4      Valores  EntitySet      Valores
5   ValoresStr  EntitySet   ValoresStr

In [6]:
metadados = ipea.api_call('http://www.ipeadata.gov.br/api/odata4/Metadados')

In [7]:
metadados.shape

(9609, 15)

In [8]:
metadados.dtypes

SERCODIGO         object
SERNOME           object
SERCOMENTARIO     object
SERATUALIZACAO    object
BASNOME           object
FNTSIGLA          object
FNTNOME           object
FNTURL            object
PERNOME           object
UNINOME           object
MULNOME           object
SERSTATUS         object
TEMCODIGO          int64
PAICODIGO         object
SERNUMERICA         bool
dtype: object

In [9]:
metadados.head()

,SERCODIGO,SERNOME,SERCOMENTARIO,SERATUALIZACAO,BASNOME,FNTSIGLA,FNTNOME,FNTURL,PERNOME,UNINOME,MULNOME,SERSTATUS,TEMCODIGO,PAICODIGO,SERNUMERICA
0,ABATE_ABPEAV,Abate - aves - peso das carcaças,O abate de animais é mensurado por sua quantid...,2023-06-06T10:40:00.023-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Tonelada,mil,A,1,BRA,True
1,ABATE_ABPEBV,Abate - bovinos - peso das carcaças,O abate de animais é mensurado por sua quantid...,2023-06-06T10:40:00.023-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Tonelada,mil,A,1,BRA,True
2,ABATE_ABPESU,Abate - suínos - peso das carcaças,O abate de animais é mensurado por sua quantid...,2023-06-06T10:40:00.023-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Tonelada,mil,A,1,BRA,True
3,ABATE_ABQUAV,Abate - aves - quantidade,O abate de animais é mensurado por sua quantid...,2023-06-06T10:40:00.023-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Cabeça,mil,A,1,BRA,True
4,ABATE_ABQUBV,Abate - bovinos - quantidade,O abate de animais é mensurado por sua quantid...,2023-06-06T10:40:00.023-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Cabeça,mil,A,1,BRA,True

In [10]:
metadados['BASNOME'].value_counts()

BASNOME
Macroeconômico    7539
Regional          1362
Social             708
Name: count, dtype: int64

In [11]:
temas = ipea.api_call('http://www.ipeadata.gov.br/api/odata4/Temas')

In [12]:
temas.head(50)

    TEMCODIGO  TEMCODIGO_PAI                        TEMNOME
0          28            NaN                   Agropecuária
1          23            NaN             Assistência social
2          10            NaN          Balanço de pagamentos
3           7            NaN                         Câmbio
4           5            NaN              Comércio exterior
5           2            NaN               Consumo e vendas
6           8            NaN               Contas nacionais
7          81            NaN               Contas Regionais
8          24            NaN             Correção monetária
9          86           37.0               Demografia Geral
10         87           37.0                 Demografia_Cor
11         88           37.0              Demografia_Gênero
12         89           37.0        Demografia_Urbano/Rural
13         54           18.0              Deputado Estadual
14         55           18.0               Deputado Federal
15         38            NaN         Desenvolvimento humano
16         85           38.0                       DH Geral
17         79           38.0                         DH_Cor
18         78           38.0                      DH_Gênero
19         80           38.0                DH_Urbano/Rural
20         11            NaN         Economia internacional
21         90           29.0                 Educação Geral
22         91           29.0                   Educação_Cor
23         92           29.0                Educação_Gênero
24         93           29.0          Educação_Urbano/Rural
25         63           18.0                     Eleitorado
26         12            NaN                        Emprego
27         19            NaN             Estoque de capital
28          6            NaN              Finanças públicas
29         39            NaN                    Financeiras
30         32            NaN                     Geográfico
31         56           18.0                     Governador
32         94           31.0                Habitação Geral
33         95           31.0                  Habitação_Cor
34         96           31.0               Habitação_Gênero
35         97           31.0         Habitação_Urbano/Rural
36         15            NaN            Indicadores sociais
37         99           40.0           Marcado Trabalho_Cor
38         98           40.0         Mercado Trabalho Geral
39        100           40.0        Mercado Trabalho_Gênero
40        101           40.0  Mercado Trabalho_Urbano/Rural
41          3            NaN                Moeda e crédito
42         27            NaN        Percepção e expectativa
43         14            NaN                      População
44          9            NaN                         Preços
45         57           18.0                       Prefeito
46         58           18.0                     Presidente
47          1            NaN                       Produção
48         16            NaN                      Projeções
49         30            NaN                          Renda

In [13]:
educacao_urbano_rural = pd.DataFrame(metadados.loc[metadados['TEMCODIGO'] == 93])

In [14]:
educacao_urbano_rural.shape

(26, 15)

In [15]:
educacao_urbano_rural.head()

,SERCODIGO,SERNOME,SERCOMENTARIO,SERATUALIZACAO,BASNOME,FNTSIGLA,FNTNOME,FNTURL,PERNOME,UNINOME,MULNOME,SERSTATUS,TEMCODIGO,PAICODIGO,SERNUMERICA
9187,ADH_E_ANOSESTUDO_RUR,Expectativa de anos de estudo aos 18 anos de i...,Número médio de anos de estudo que uma geração...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,Ano,None,None,93,BRA,True
9188,ADH_E_ANOSESTUDO_URB,Expectativa de anos de estudo aos 18 anos de i...,Número médio de anos de estudo que uma geração...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,Ano,None,None,93,BRA,True
9189,ADH_T_ANALF11A14_RUR,Taxa de analfabetismo da população de 11 a 14 ...,Razão entre a população de 11 a 14 anos de ida...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,(%),None,None,93,BRA,True
9190,ADH_T_ANALF11A14_URB,Taxa de analfabetismo da população de 11 a 14 ...,Razão entre a população de 11 a 14 anos de ida...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,(%),None,None,93,BRA,True
9191,ADH_T_ANALF15M_RUR,Taxa de analfabetismo da população de 15 anos ...,Razão entre a população de 15 anos ou mais de ...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,(%),None,None,93,BRA,True

In [16]:
educacao_urbano_rural['SERATUALIZACAO'] = pd.to_datetime(educacao_urbano_rural['SERATUALIZACAO'])

In [17]:
educacao_urbano_rural.index.reset_index()

AttributeError: 'Index' object has no attribute 'reset_index'

In [ ]:
educacao_urbano_rural.head()

,SERCODIGO,SERNOME,SERCOMENTARIO,SERATUALIZACAO,BASNOME,FNTSIGLA,FNTNOME,FNTURL,PERNOME,UNINOME,MULNOME,SERSTATUS,TEMCODIGO,PAICODIGO,SERNUMERICA
9187,ADH_E_ANOSESTUDO_RUR,Expectativa de anos de estudo aos 18 anos de i...,Número médio de anos de estudo que uma geração...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,Ano,None,None,93,BRA,True
9188,ADH_E_ANOSESTUDO_URB,Expectativa de anos de estudo aos 18 anos de i...,Número médio de anos de estudo que uma geração...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,Ano,None,None,93,BRA,True
9189,ADH_T_ANALF11A14_RUR,Taxa de analfabetismo da população de 11 a 14 ...,Razão entre a população de 11 a 14 anos de ida...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,(%),None,None,93,BRA,True
9190,ADH_T_ANALF11A14_URB,Taxa de analfabetismo da população de 11 a 14 ...,Razão entre a população de 11 a 14 anos de ida...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,(%),None,None,93,BRA,True
9191,ADH_T_ANALF15M_RUR,Taxa de analfabetismo da população de 15 anos ...,Razão entre a população de 15 anos ou mais de ...,2023-03-07T13:50:57-03:00,Social,IPEA/ADH Censo IBGE,Atlas do Desenvolvimento Humano (Censo Demográ...,www.atlasbrasil.org.br,Decenal,(%),None,None,93,BRA,True

In [19]:
sinopse = pd.read_excel('./Sinopse_Estatistica_da_Educação_Basica_2022/Sinopse_Estatistica_da_Educação_Basica_2022.xlsx')

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.